# Test your FastAPI endpoints

### root endpoint
GET https://127.0.0.1/
Accept: text/html

> {%
    client.test("Status code is 200", function() {
        client.assert(response.status === 200, "Expected 200 OK");
    });
    client.test("Content-Type is text/html", function() {
        client.assert(response.headers.valueOf("Content-Type") === "text/html; charset=utf-8", "Expected text/html");
    });
%}

### favicon
GET https://127.0.0.1/favicon.ico
Accept: image/x-icon

> {%
    client.test("Status code is 200", function() {
        client.assert(response.status === 200, "Expected 200 OK");
    });
    client.test("Content-Type is image/x-icon", function() {
        client.assert(response.headers.valueOf("Content-Type") === "image/x-icon", "Expected image/x-icon");
    });
%}

### process-time
# ensure process time header is present
GET https://127.0.0.1/
Accept: text/html

> {%
    client.test("Response should have X-Process-Time header", function() {
        client.assert(response.headers.valueOf('x-process-time') != null,
            "X-Process-Time header not found.");
        client.assert(!isNaN(parseFloat(response.headers.valueOf('x-process-time'))),
            "X-Process-Time header is not number: " + response.headers.valueOf('x-process-time'));
    });
%}

### shared listing
# ensure the directory listing under /shared is available
GET https://127.0.0.1/shared/
Accept: text/html

> {%
    client.test("Status code is 200", function() {
        client.assert(response.status === 200, "Expected 200 OK");
    });
    client.test("Content-Type is text/html", function() {
        client.assert(response.headers.valueOf("Content-Type") === "text/html; charset=utf-8", "Expected text/html");
    });
%}

### chat app
# ensure the chat app is available
GET https://127.0.0.1/apps/chat
Accept: text/html

> {%
    client.test("Status code is 200", function() {
        client.assert(response.status === 200, "Expected 200 OK");
    });
    client.test("Content-Type is text/html", function() {
        client.assert(response.headers.valueOf("Content-Type") === "text/html; charset=utf-8", "Expected text/html");
    });
%}
