name: Dih
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: deployment
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /home/opc/gws2
            git pull origin main
            source venv/bin/activate
            pip install -r requirements.txt
            sudo systemctl restart gws2
            sudo nginx -t && sudo systemctl reload nginx
